"""add quality_checks to pipeline_runs

Revision ID: 5b624203dc68
Revises: 6891d636af9a
Create Date: 2026-08-27 13:22:15.548523

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b624203dc68'
down_revision: Union[str, None] = '6891d636af9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_runs', sa.Column('quality_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_runs', 'quality_checks')
    # ### end Alembic commands ###
