"""add pipeline review tracking

Revision ID: 6891d636af9a
Revises: d1f4a9b8c2e0
Create Date: 2026-08-22 13:11:51.409648

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '6891d636af9a'
down_revision: Union[str, None] = 'd1f4a9b8c2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
